import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useSeo } from "@/lib/seo";

function Shell({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="u-container max-w-prose pt-[clamp(6.5rem,12vh,8rem)] pb-16 sm:pb-20">
      <Link
        to="/"
        className="inline-flex items-center gap-2 text-[0.9rem] font-medium text-muted transition-colors hover:text-ink"
      >
        <ArrowLeft size={16} /> Back to the refiner
      </Link>
      <h1 className="mt-6 font-display text-[2.3rem] font-semibold tracking-tighter">{title}</h1>
      <div className="mt-8 space-y-5 leading-relaxed text-muted [&_h2]:mt-9 [&_h2]:font-display [&_h2]:text-[1.3rem] [&_h2]:font-semibold [&_h2]:tracking-tight [&_h2]:text-ink [&_strong]:font-semibold [&_strong]:text-ink">
        {children}
      </div>
    </div>
  );
}

export function Privacy() {
  useSeo({
    title: "Privacy — Hone",
    description:
      "Hone does not store your prompts. They are sent to the AI model to be refined and returned, and nothing is logged or saved.",
    canonical: "https://honeprompt.vercel.app/privacy",
  });
  return (
    <Shell title="Privacy">
      <p className="text-[0.82rem] uppercase tracking-wider text-muted">Last updated July 2026</p>
      <p>
        Hone is a free, open-source tool with no accounts and no tracking of who you are. This
        page explains, in plain language, exactly what happens to the text you paste in.
      </p>

      <h2>What we do with your prompt</h2>
      <p>
        When you refine a prompt, the text is sent to our server, which forwards it to an AI model
        (Groq, running an open-weight model) purely to rewrite it. The rewritten result is returned
        to your browser. <strong>We do not store your prompt or the result</strong>, we do not log
        their contents, and we do not use them to train anything.
      </p>

      <h2>What we do not collect</h2>
      <p>
        No name, no email, no account, no cookies for advertising. We do not build a profile of you.
        A short-lived, in-memory rate limit uses your network address only to stop abuse of this free
        service, and it is not stored beyond that moment.
      </p>

      <h2>The AI provider</h2>
      <p>
        Refining relies on Groq's API. Your prompt is subject to their processing terms for the brief
        moment it is refined. We send only the prompt text and nothing that identifies you.
      </p>

      <h2>Hosting</h2>
      <p>
        The site is hosted on Vercel, which may collect standard, aggregate request logs (such as
        timing and status codes) for operating the service. Those are Vercel's platform logs, not
        content we keep.
      </p>

      <h2>Open source</h2>
      <p>
        Because the entire tool is open source, you can read exactly how it handles your text, or run
        your own copy with your own key. Nothing is hidden.
      </p>

      <h2>Contact</h2>
      <p>
        Questions? Open an issue on the GitHub repository, or email{" "}
        <strong>carlos1010.peter@gmail.com</strong>.
      </p>
    </Shell>
  );
}

export function Terms() {
  useSeo({
    title: "Terms — Hone",
    description: "The simple terms of use for Hone, a free and open-source prompt refiner.",
    canonical: "https://honeprompt.vercel.app/terms",
  });
  return (
    <Shell title="Terms of use">
      <p className="text-[0.82rem] uppercase tracking-wider text-muted">Last updated July 2026</p>
      <p>
        Hone is provided free of charge, as is, for anyone to use. By using it you agree to
        these short terms.
      </p>

      <h2>The service</h2>
      <p>
        Hone rewrites the prompt you paste into a cleaner, more structured version. It is a
        best-effort tool: the output is generated by an AI model and may not always be perfect.
        Review the result before you use it.
      </p>

      <h2>Acceptable use</h2>
      <p>
        Do not use Hone to process unlawful content, to abuse the service with automated bulk
        traffic, or to attempt to break, overload or reverse the rate limits. The service may be
        throttled or unavailable at any time.
      </p>

      <h2>No warranty</h2>
      <p>
        The tool is provided without warranties of any kind. To the fullest extent permitted by law,
        the author is not liable for any loss arising from your use of the refined prompts or the
        service.
      </p>

      <h2>Your content</h2>
      <p>
        You keep all rights to the prompts you paste and to the refined results. We claim nothing and
        store nothing. See the <Link to="/privacy" className="text-ink underline underline-offset-2">Privacy</Link> page.
      </p>

      <h2>License</h2>
      <p>
        The Hone source code is released under the MIT license and available on GitHub. You are
        free to use, modify and self-host it under those terms.
      </p>
    </Shell>
  );
}
